name: Tests
on: push

jobs:
  testing:
    name: running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/setup-python@v2
        with:
          python-version: 3.8